Feat: Add multisig views
DEIPworld/deip-wallet pull request #30
Opened 2022-06-21 07:33 UTC by IgorNovitskiy

2022-06-22 09:23 UTC, euheny requested changes

2022-06-22 09:23 UTC, euheny commented on src/components/DisplayAddress/DisplayAddress.tsx
> +        {!props.hideCopyButton && (
вынести в отдельный рендер-метод. стараемся не использовать вложенные конструкции в jsx

2022-06-22 09:23 UTC, euheny commented on src/components/DisplayAddress/DisplayAddress.tsx
> +        {!props.hideCopyButton && (
вынести в отдельный рендер-метод. стараемся не использовать вложенные конструкции в jsx

2022-06-22 09:23 UTC, euheny commented on src/components/MultisigAccountCreate/AddSignatoryModal.tsx
> +    watchEffect(() => {
мне кажется лучше нулить форму по закрытию модалки, а не по открытию

2022-06-22 09:23 UTC, euheny commented on src/components/MultisigAccountCreate/AddSignatoryModal.tsx
> +            singleLine
зачем данные пропсы? вроде же стандартное отображение норм было (поле ниже тот же вопрос)

2022-06-22 09:23 UTC, euheny commented on src/components/MultisigActionReceive/MultisigActionReceive.tsx
> +import { defineComponent } from 'vue';
СОзданный ранее ресив не подходит?

2022-06-22 09:23 UTC, euheny commented on src/components/MultisigApprovals/ApprovalDetailsModal.tsx
> +    const renderSignatories = () => (
что за моки вместо данных?

2022-06-23 08:33 UTC, IgorNovitskiy commented on src/components/MultisigApprovals/ApprovalDetailsModal.tsx
> +    const renderSignatories = () => (
заглушка пока не будет готова часть с созданием транзакций. Будет доделана в следующем пре

2022-06-24 09:25 UTC, euheny approved these changes

2022-06-24 09:40 UTC, merged