Fix: update styles
DEIPworld/deip-wallet pull request #33
Opened 2022-06-28 11:27 UTC by IgorNovitskiy

2022-06-28 11:39 UTC, euheny requested changes

2022-06-28 11:39 UTC, euheny commented on src/components/Header/Header.tsx
> +      <VBtn width="180" color="secondary-btn" class="text-capitalize" variant="contained" size="small" rounded={false}>
зачем изменение кейса?

2022-06-28 11:39 UTC, euheny commented on src/components/MultisigApprovals/MultisigApprovalDetails.tsx
> +          <div class="d-flex justify-space-between align-center">
лучше использовать спэйсер <VSpacer /> дабы потенциально легче было контролить. добавишь например еще одну кнопку и все поедет

2022-06-28 11:41 UTC, euheny commented on src/components/Header/Header.tsx
> +      <VBtn width="180" color="secondary-btn" class="text-capitalize" variant="contained" size="small" rounded={false}>
кнопки имеют стиль и кейс в низ константен. откуда возникла необходимость его менять?

2022-06-28 11:46 UTC, IgorNovitskiy commented on src/components/Header/Header.tsx
> +      <VBtn width="180" color="secondary-btn" class="text-capitalize" variant="contained" size="small" rounded={false}>
требование задачи (первый пункт) - https://deip.atlassian.net/jira/software/projects/DW/boards/3?selectedIssue=DW-10

2022-06-29 08:44 UTC, IgorNovitskiy commented on src/components/Header/Header.tsx
> +      <VBtn width="180" color="secondary-btn" class="text-capitalize" variant="contained" size="small" rounded={false}>
Требования обновили. Убрал капитализацию

2022-06-29 12:25 UTC, euheny approved these changes

2022-06-29 12:40 UTC, merged